import type { FurnitureItem, FurnitureTemplate, RoomConfig } from "./types";

export const defaultRoom: RoomConfig = {
  width: 5.85,
  depth: 6.02,
  foyer: {
    width: 1.45,
    depth: 2,
    offsetY: 1.1,
  },
};

export const furnitureTemplates: FurnitureTemplate[] = [
  {
    id: "sectional-sofa",
    name: "三人沙发",
    category: "坐具",
    width: 2.8,
    depth: 0.95,
    clearance: 0.12,
    color: "#5f7f72",
  },
  {
    id: "tv-console",
    name: "电视柜",
    category: "收纳",
    width: 2.4,
    depth: 0.42,
    clearance: 0.06,
    color: "#374151",
  },
  {
    id: "coffee-table",
    name: "小孩游戏桌",
    category: "桌几",
    width: 1.2,
    depth: 0.65,
    clearance: 0.18,
    color: "#c47b4f",
  },
  {
    id: "dining-table",
    name: "四人餐桌",
    category: "餐区",
    width: 1.6,
    depth: 0.9,
    clearance: 0.42,
    color: "#9a6b45",
  },
  {
    id: "lounge-chair",
    name: "单椅",
    category: "坐具",
    width: 0.78,
    depth: 0.78,
    clearance: 0.12,
    color: "#457b9d",
  },
  {
    id: "sideboard",
    name: "边柜",
    category: "收纳",
    width: 1.6,
    depth: 0.42,
    clearance: 0.08,
    color: "#806443",
  },
  {
    id: "entry-cabinet",
    name: "玄关柜",
    category: "收纳",
    width: 1.15,
    depth: 0.34,
    clearance: 0.06,
    color: "#5c544b",
  },
  {
    id: "plant",
    name: "绿植",
    category: "装饰",
    width: 0.55,
    depth: 0.55,
    clearance: 0.05,
    color: "#4d8a57",
  },
  {
    id: "rug",
    name: "地毯",
    category: "软装",
    width: 2.6,
    depth: 1.75,
    clearance: 0,
    color: "#d8b76d",
    collidable: false,
  },
];

export const initialFurniture: FurnitureItem[] = [
  {
    ...furnitureTemplates[1],
    itemId: "item-tv-console",
    templateId: "tv-console",
    x: 2.95,
    y: 0.38,
    rotation: 0,
  },
  {
    ...furnitureTemplates[0],
    itemId: "item-sofa",
    templateId: "sectional-sofa",
    x: 2.05,
    y: 4.88,
    rotation: 0,
  },
  {
    ...furnitureTemplates[2],
    itemId: "item-coffee-table",
    templateId: "coffee-table",
    x: 2.05,
    y: 3.65,
    rotation: 0,
  },
  {
    ...furnitureTemplates[3],
    itemId: "item-dining-table",
    templateId: "dining-table",
    x: 4.45,
    y: 2.15,
    rotation: 0,
  },
  {
    ...furnitureTemplates[6],
    itemId: "item-entry-cabinet",
    templateId: "entry-cabinet",
    x: 7.04,
    y: 2.1,
    rotation: 90,
  },
  {
    id: "custom-cabinet-vertical",
    name: "定制柜A",
    category: "定制柜",
    width: 0.55,
    depth: 2.75,
    clearance: 0,
    color: "#6b5a45",
    itemId: "item-custom-cabinet-vertical",
    templateId: "custom-cabinet-vertical",
    x: 5.575,
    y: 4.64,
    rotation: 0,
    locked: true,
  },
  {
    id: "custom-cabinet-horizontal",
    name: "定制柜B",
    category: "定制柜",
    width: 1.38,
    depth: 0.55,
    clearance: 0,
    color: "#6b5a45",
    itemId: "item-custom-cabinet-horizontal",
    templateId: "custom-cabinet-horizontal",
    x: 6.6,
    y: 2.825,
    rotation: 0,
    locked: true,
  },
  {
    ...furnitureTemplates[8],
    itemId: "item-rug",
    templateId: "rug",
    x: 2.05,
    y: 3.9,
    rotation: 0,
  },
];
